Repository rlfrkdms1/Prog-rangers, pull requests merged in 2023-08, with the labels that each got.

#10 일반 로그인, 회원가입 기능
  backend/build.gradle
  backend/src/main/java/com/prograngers/backend/AuthInterceptor.java
  backend/src/main/java/com/prograngers/backend/AuthResult.java
  backend/src/main/java/com/prograngers/backend/Encrypt.java
  backend/src/main/java/com/prograngers/backend/JwtTokenProvider.java
  backend/src/main/java/com/prograngers/backend/LoggedInArgumentResolver.java
  backend/src/main/java/com/prograngers/backend/LoggedInMember.java
  backend/src/main/java/com/prograngers/backend/Login.java
  backend/src/main/java/com/prograngers/backend/RefreshToken.java
  backend/src/main/java/com/prograngers/backend/WebConfig.java
  backend/src/main/java/com/prograngers/backend/config/QueryDslConfig.java
  backend/src/main/java/com/prograngers/backend/controller/MemberController.java
  backend/src/main/java/com/prograngers/backend/dto/FailToDecodeException.java
  backend/src/main/java/com/prograngers/backend/dto/FailToEncodeException.java
  backend/src/main/java/com/prograngers/backend/dto/LoginRequest.java
  backend/src/main/java/com/prograngers/backend/dto/SignUpRequest.java
  backend/src/main/java/com/prograngers/backend/entity/Member.java
  backend/src/main/java/com/prograngers/backend/exception/CustomException.java
  backend/src/main/java/com/prograngers/backend/exception/ErrorCode.java
  backend/src/main/java/com/prograngers/backend/exception/ExpiredTokenException.java
  backend/src/main/java/com/prograngers/backend/exception/InvalidException.java
  backend/src/main/java/com/prograngers/backend/exception/InvalidPasswordException.java
  backend/src/main/java/com/prograngers/backend/exception/NotExistTokenException.java
  backend/src/main/java/com/prograngers/backend/exception/RefreshTokenNotExistException.java
  backend/src/main/java/com/prograngers/backend/exception/RefreshTokenNotFoundException.java
  backend/src/main/java/com/prograngers/backend/exception/UnAuthorizationException.java
  backend/src/main/java/com/prograngers/backend/exception/enumtype/AlgorithmNotFoundException.java
  backend/src/main/java/com/prograngers/backend/exception/enumtype/DataStructureNotFoundException.java
  backend/src/main/java/com/prograngers/backend/exception/enumtype/EnumTypeException.java
  backend/src/main/java/com/prograngers/backend/exception/enumtype/LevelNotFoundException.java
  backend/src/main/java/com/prograngers/backend/exception/notfound/MemberNotFoundException.java
  backend/src/main/java/com/prograngers/backend/exception/notfound/NotFoundException.java
  backend/src/main/java/com/prograngers/backend/exception/notfound/ProblemLinkNotFoundException.java
  backend/src/main/java/com/prograngers/backend/exception/notfound/SolutionNotFoundException.java
  backend/src/main/java/com/prograngers/backend/repository/MemberRepository.java
  backend/src/main/java/com/prograngers/backend/repository/RefreshTokenRepository.java
  backend/src/main/java/com/prograngers/backend/service/MemberService.java
  backend/src/main/resources/application.properties
Labels: ➕ feat

#14 🗣️ 카카오 로그인 기능 추가
  backend/build.gradle
  backend/src/main/java/com/prograngers/backend/BackendApplication.java
  backend/src/main/java/com/prograngers/backend/config/JpaConfig.java
  backend/src/main/java/com/prograngers/backend/config/WebClientConfig.java
  backend/src/main/java/com/prograngers/backend/config/WebConfig.java
  backend/src/main/java/com/prograngers/backend/controller/GlobalExceptionHandler.java
  backend/src/main/java/com/prograngers/backend/controller/MemberController.java
  backend/src/main/java/com/prograngers/backend/controller/RefreshCookieProvider.java
  backend/src/main/java/com/prograngers/backend/controller/auth/AuthController.java
  backend/src/main/java/com/prograngers/backend/controller/auth/AuthInterceptor.java
  backend/src/main/java/com/prograngers/backend/controller/auth/LoggedInArgumentResolver.java
  backend/src/main/java/com/prograngers/backend/controller/auth/LoggedInMember.java
  backend/src/main/java/com/prograngers/backend/controller/auth/Login.java
  backend/src/main/java/com/prograngers/backend/dto/request/auth/LoginRequest.java
  backend/src/main/java/com/prograngers/backend/dto/request/auth/SignUpRequest.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/KakaoAccount.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/KakaoTokenResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/KakaoUserInfoResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/Profile.java
  backend/src/main/java/com/prograngers/backend/dto/result/AuthResult.java
  backend/src/main/java/com/prograngers/backend/entity/Member.java
  backend/src/main/java/com/prograngers/backend/entity/MemberType.java
  backend/src/main/java/com/prograngers/backend/exception/ErrorCode.java
  backend/src/main/java/com/prograngers/backend/exception/InvalidException.java
  backend/src/main/java/com/prograngers/backend/exception/InvalidPasswordException.java
  backend/src/main/java/com/prograngers/backend/exception/UnAuthorizationException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/ExpiredTokenException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/FailToDecodeException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/FailToEncodeException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/IncorrectPasswordException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/NotExistTokenException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/RefreshTokenNotExistException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/RefreshTokenNotFoundException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/UnAuthorizationException.java
  backend/src/main/java/com/prograngers/backend/repository/RefreshTokenRepository.java
  backend/src/main/java/com/prograngers/backend/repository/member/MemberRepository.java
  backend/src/main/java/com/prograngers/backend/service/auth/AuthService.java
  backend/src/main/java/com/prograngers/backend/service/auth/Encrypt.java
  backend/src/main/java/com/prograngers/backend/service/auth/JwtTokenProvider.java
  backend/src/main/java/com/prograngers/backend/service/auth/KakaoOauth.java
  backend/src/main/java/com/prograngers/backend/service/auth/OauthConstant.java
  backend/src/main/java/com/prograngers/backend/service/auth/RefreshToken.java
  backend/src/main/resources/static/index.html
Labels: ➕ feat

#21 네이버 로그인 기능
  backend/src/main/java/com/prograngers/backend/controller/auth/AuthController.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/google/GoogleTokenResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/google/GoogleUserInfoResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/kakao/KakaoAccount.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/kakao/KakaoTokenResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/kakao/KakaoUserInfoResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/kakao/Profile.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/naver/NaverTokenResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/naver/NaverUserInfoResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/naver/Response.java
  backend/src/main/java/com/prograngers/backend/entity/Member.java
  backend/src/main/java/com/prograngers/backend/service/auth/AuthService.java
  backend/src/main/java/com/prograngers/backend/service/auth/GoogleOauth.java
  backend/src/main/java/com/prograngers/backend/service/auth/KakaoOauth.java
  backend/src/main/java/com/prograngers/backend/service/auth/NaverOauth.java
  backend/src/main/resources/static/index.html
Labels: ➕ feat

#29 👤 로그인 및 회원 가입 기능 수정
  backend/src/main/java/com/prograngers/backend/controller/GlobalExceptionHandler.java
  backend/src/main/java/com/prograngers/backend/controller/auth/AuthController.java
  backend/src/main/java/com/prograngers/backend/dto/request/auth/SignUpRequest.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/LoginResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/google/GoogleUserInfoResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/kakao/KakaoUserInfoResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/naver/NaverUserInfoResponse.java
  backend/src/main/java/com/prograngers/backend/dto/solution/reqeust/SolutionPostRequest.java
  backend/src/main/java/com/prograngers/backend/entity/Comment.java
  backend/src/main/java/com/prograngers/backend/entity/Likes.java
  backend/src/main/java/com/prograngers/backend/entity/Review.java
  backend/src/main/java/com/prograngers/backend/entity/Solution.java
  backend/src/main/java/com/prograngers/backend/entity/constants/JudgeConstant.java
  backend/src/main/java/com/prograngers/backend/entity/member/Member.java
  backend/src/main/java/com/prograngers/backend/entity/member/MemberType.java
  backend/src/main/java/com/prograngers/backend/exception/ErrorCode.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/AlreadyExistMemberException.java
  backend/src/main/java/com/prograngers/backend/repository/member/MemberRepository.java
  backend/src/main/java/com/prograngers/backend/repository/solution/SolutionRepository.java
  backend/src/main/java/com/prograngers/backend/service/SolutionService.java
  backend/src/main/java/com/prograngers/backend/service/auth/AuthService.java
  backend/src/main/java/com/prograngers/backend/service/auth/oauth/GoogleOauth.java
  backend/src/main/java/com/prograngers/backend/service/auth/oauth/KakaoOauth.java
  backend/src/main/java/com/prograngers/backend/service/auth/oauth/MultiValueMapConverter.java
  backend/src/main/java/com/prograngers/backend/service/auth/oauth/NaverOauth.java
  backend/src/test/java/com/prograngers/backend/fixture/CommentFixture.java
  backend/src/test/java/com/prograngers/backend/fixture/MemberFixture.java
  backend/src/test/java/com/prograngers/backend/fixture/ProblemFixture.java
  backend/src/test/java/com/prograngers/backend/fixture/SolutionFixture.java
  backend/src/test/java/com/prograngers/backend/repository/problem/ProblemRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/repository/solution/SolutionListSolutionRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/service/CommentServiceTest.java
  backend/src/test/java/com/prograngers/backend/service/SolutionListSolutionServiceTest.java
Labels: ♻ refactor

#31 [FIX] 🐞
  backend/src/main/java/com/prograngers/backend/controller/auth/AuthController.java
  backend/src/main/java/com/prograngers/backend/controller/auth/AuthInterceptor.java
  backend/src/main/java/com/prograngers/backend/controller/auth/LoggedInArgumentResolver.java
  backend/src/main/java/com/prograngers/backend/controller/auth/LoggedInMember.java
  backend/src/main/java/com/prograngers/backend/exception/ErrorCode.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/NotExistAccessTokenException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/NotExistRefreshTokenException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/NotExistTokenException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/RefreshTokenNotExistException.java
Labels: 🐞 bug

#32 Fix: Solution 관련 버그를 수정했습니다
  backend/src/main/java/com/prograngers/backend/controller/CommentController.java
  backend/src/main/java/com/prograngers/backend/controller/GlobalExceptionHandler.java
  backend/src/main/java/com/prograngers/backend/controller/ProblemController.java
  backend/src/main/java/com/prograngers/backend/controller/ReviewController.java
  backend/src/main/java/com/prograngers/backend/controller/SolutionController.java
  backend/src/main/java/com/prograngers/backend/dto/solution/reqeust/ScarpSolutionPostRequest.java
  backend/src/main/java/com/prograngers/backend/dto/solution/reqeust/SolutionPatchRequest.java
  backend/src/main/java/com/prograngers/backend/dto/solution/reqeust/SolutionPostRequest.java
  backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionDetailResponse.java
  backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionDetailSolution.java
  backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionListResponse.java
  backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionUpdateFormResponse.java
  backend/src/main/java/com/prograngers/backend/entity/Comment.java
  backend/src/main/java/com/prograngers/backend/entity/Problem.java
  backend/src/main/java/com/prograngers/backend/entity/Review.java
  backend/src/main/java/com/prograngers/backend/entity/Solution.java
  backend/src/main/java/com/prograngers/backend/entity/constants/LevelConstant.java
  backend/src/main/java/com/prograngers/backend/entity/constants/SortConstant.java
  backend/src/main/java/com/prograngers/backend/exception/ErrorCode.java
  backend/src/main/java/com/prograngers/backend/exception/enumtype/SortTypeNotFoundException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/MemberUnAuthorizedException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/UnAuthorizationException.java
  backend/src/main/java/com/prograngers/backend/repository/likes/LikesRepository.java
  backend/src/main/java/com/prograngers/backend/repository/solution/QueryDslSolutionRepository.java
  backend/src/main/java/com/prograngers/backend/repository/solution/QueryDslSolutionRepositoryImpl.java
  backend/src/main/java/com/prograngers/backend/repository/solution/SolutionRepository.java
  backend/src/main/java/com/prograngers/backend/service/CommentService.java
  backend/src/main/java/com/prograngers/backend/service/SolutionService.java
  backend/src/test/java/com/prograngers/backend/fixture/MemberFixture.java
  backend/src/test/java/com/prograngers/backend/fixture/ProblemFixture.java
  backend/src/test/java/com/prograngers/backend/fixture/SolutionFixture.java
  backend/src/test/java/com/prograngers/backend/repository/solution/SolutionRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/service/CommentServiceTest.java
  backend/src/test/java/com/prograngers/backend/service/SolutionListSolutionServiceTest.java
Labels: 🐞 bug

#35 [FEAT] 🐥 로그아웃, 닉네임 관련 로직, 예외 핸들 추가
  backend/src/main/java/com/prograngers/backend/controller/RefreshCookieProvider.java
  backend/src/main/java/com/prograngers/backend/controller/auth/AuthController.java
  backend/src/main/java/com/prograngers/backend/controller/auth/AuthInterceptor.java
  backend/src/main/java/com/prograngers/backend/controller/auth/RefreshCookieProvider.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/google/GoogleUserInfoResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/kakao/KakaoUserInfoResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/naver/NaverUserInfoResponse.java
  backend/src/main/java/com/prograngers/backend/dto/response/auth/naver/Response.java
  backend/src/main/java/com/prograngers/backend/entity/member/Member.java
  backend/src/main/java/com/prograngers/backend/exception/ErrorCode.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/AlreadyExistNicknameException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/FailedSignatureTokenException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/IncorrectCodeInNaverLoginException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/IncorrectIssuerTokenException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/IncorrectlyConstructedTokenException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/InvalidAccessTokenException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/MissingIssuerTokenException.java
  backend/src/main/java/com/prograngers/backend/exception/unauthorization/UnsupportedTokenException.java
  backend/src/main/java/com/prograngers/backend/repository/member/MemberRepository.java
  backend/src/main/java/com/prograngers/backend/service/auth/AuthService.java
  backend/src/main/java/com/prograngers/backend/service/auth/GenerateNicknameResponse.java
  backend/src/main/java/com/prograngers/backend/service/auth/JwtTokenProvider.java
  backend/src/main/java/com/prograngers/backend/service/auth/NicknameGenerator.java
  backend/src/main/java/com/prograngers/backend/service/auth/oauth/NaverOauth.java
  backend/src/main/resources/db/migration/V1__init.sql
Labels: ➕ feat, ⚙ chore

#40 Fix/39 Entity 필드 변경, 테스트 코드 수정
  backend/src/main/java/com/prograngers/backend/dto/solution/reqeust/ScarpSolutionPostRequest.java
  backend/src/main/java/com/prograngers/backend/dto/solution/reqeust/SolutionPostRequest.java
  backend/src/main/java/com/prograngers/backend/entity/Comment.java
  backend/src/main/java/com/prograngers/backend/entity/Problem.java
  backend/src/main/java/com/prograngers/backend/entity/Review.java
  backend/src/main/java/com/prograngers/backend/entity/Solution.java
  backend/src/main/java/com/prograngers/backend/exception/ErrorCode.java
  backend/src/main/java/com/prograngers/backend/repository/problem/QueryDslProblemRepositoryImpl.java
  backend/src/main/java/com/prograngers/backend/repository/review/ReviewRepository.java
  backend/src/main/java/com/prograngers/backend/repository/solution/QueryDslSolutionRepositoryImpl.java
  backend/src/main/java/com/prograngers/backend/service/CommentService.java
  backend/src/main/java/com/prograngers/backend/service/ReviewService.java
  backend/src/test/java/com/prograngers/backend/fixture/ProblemFixture.java
  backend/src/test/java/com/prograngers/backend/fixture/SolutionFixture.java
  backend/src/test/java/com/prograngers/backend/repository/comment/CommentRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/repository/problem/ProblemListProblemRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/repository/solution/SolutionRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/service/CommentServiceTest.java
Labels: 🐞 bug

#41 [FEAT] 👤 마이페이지의 계정정보 관련 기능 추가
  backend/src/main/java/com/prograngers/backend/controller/MemberController.java
  backend/src/main/java/com/prograngers/backend/dto/request/UpdateMemberAccountInfoRequest.java
  backend/src/main/java/com/prograngers/backend/dto/response/member/MemberAccountInfoResponse.java
  backend/src/main/java/com/prograngers/backend/entity/member/Member.java
  backend/src/main/java/com/prograngers/backend/exception/ErrorCode.java
  backend/src/main/java/com/prograngers/backend/exception/badrequest/BlankNicknameException.java
  backend/src/main/java/com/prograngers/backend/exception/badrequest/InvalidValueException.java
  backend/src/main/java/com/prograngers/backend/service/MemberService.java
  backend/src/main/java/com/prograngers/backend/service/auth/AuthService.java
  backend/src/main/java/com/prograngers/backend/service/auth/Encrypt.java
  backend/src/main/java/com/prograngers/backend/support/Encrypt.java
Labels: ➕ feat

#43 [FIX] Solution, Problem 정렬 쿼리 수정
  backend/src/main/java/com/prograngers/backend/dto/solution/reqeust/ScarpSolutionPostRequest.java
  backend/src/main/java/com/prograngers/backend/repository/problem/QueryDslProblemRepositoryImpl.java
  backend/src/main/java/com/prograngers/backend/repository/solution/QueryDslSolutionRepositoryImpl.java
  backend/src/test/java/com/prograngers/backend/fixture/SolutionFixture.java
  backend/src/test/java/com/prograngers/backend/repository/comment/CommentRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/repository/problem/ProblemListProblemRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/repository/solution/SolutionRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/service/SolutionListSolutionServiceTest.java
Labels: 🐞 bug, 🌞 backend

#54 [FEAT] 타인 프로필 보기 화면
  .DS_Store
  backend/src/main/java/com/prograngers/backend/controller/MemberController.java
  backend/src/main/java/com/prograngers/backend/dto/member/response/MemberProfileProblemSolution.java
  backend/src/main/java/com/prograngers/backend/dto/member/response/MemberProfileResponse.java
  backend/src/main/java/com/prograngers/backend/dto/problem/response/ProblemListProblem.java
  backend/src/main/java/com/prograngers/backend/dto/review/response/Line.java
  backend/src/main/java/com/prograngers/backend/dto/review/response/Review.java
  backend/src/main/java/com/prograngers/backend/entity/Badge.java
  backend/src/main/java/com/prograngers/backend/entity/Follow.java
  backend/src/main/java/com/prograngers/backend/entity/Problem.java
  backend/src/main/java/com/prograngers/backend/entity/constants/BadgeConstant.java
  backend/src/main/java/com/prograngers/backend/repository/badge/BadgeRepository.java
  backend/src/main/java/com/prograngers/backend/repository/follow/FollowRepository.java
  backend/src/main/java/com/prograngers/backend/repository/follow/QueryDslFollowRepository.java
  backend/src/main/java/com/prograngers/backend/repository/follow/QueryDslFollowRepositoryImpl.java
  backend/src/main/java/com/prograngers/backend/repository/solution/QueryDslSolutionRepository.java
  backend/src/main/java/com/prograngers/backend/repository/solution/QueryDslSolutionRepositoryImpl.java
  backend/src/main/java/com/prograngers/backend/repository/solution/SolutionRepository.java
  backend/src/main/java/com/prograngers/backend/service/MemberService.java
Labels: ➕ feat, 🌞 backend

#61 Feat/login signup validation
  frontend/Prog-rangers-main/src/components/SignIn/DefaultSignInForm.jsx
  frontend/Prog-rangers-main/src/components/SignUp/SignUpForm.jsx
  frontend/Prog-rangers-main/src/components/common/ErrorText.jsx
  frontend/Prog-rangers-main/src/styles/signUpPage.js
Labels: ➕ feat, 🌝 frontend

#57 [FEAT] 좋아요 누르기, 취소
  backend/src/main/java/com/prograngers/backend/controller/GlobalExceptionHandler.java
  backend/src/main/java/com/prograngers/backend/controller/LikesController.java
  backend/src/main/java/com/prograngers/backend/exception/ErrorCode.java
  backend/src/main/java/com/prograngers/backend/exception/badrequest/AlreadyExistsException.java
  backend/src/main/java/com/prograngers/backend/exception/badrequest/LikesAlreadyExistsException.java
  backend/src/main/java/com/prograngers/backend/exception/notfound/LikesNotFoundException.java
  backend/src/main/java/com/prograngers/backend/repository/likes/LikesRepository.java
  backend/src/main/java/com/prograngers/backend/service/LikesService.java
  backend/src/main/java/com/prograngers/backend/support/Encrypt.java
  backend/src/test/java/com/prograngers/backend/repository/comment/CommentRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/repository/solution/SolutionRepositoryTest.java
Labels: ➕ feat, 🌞 backend

#64 [FIX] 픽스처 수정
  backend/src/main/java/com/prograngers/backend/entity/problem/Problem.java
  backend/src/main/java/com/prograngers/backend/service/LikesService.java
  backend/src/test/java/com/prograngers/backend/fixture/CommentFixture.java
  backend/src/test/java/com/prograngers/backend/fixture/MemberFixture.java
  backend/src/test/java/com/prograngers/backend/fixture/ProblemFixture.java
  backend/src/test/java/com/prograngers/backend/fixture/SolutionFixture.java
  backend/src/test/java/com/prograngers/backend/repository/comment/CommentRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/repository/problem/ProblemListProblemRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/repository/solution/SolutionRepositoryTest.java
  backend/src/test/java/com/prograngers/backend/service/CommentServiceTest.java
  backend/src/test/java/com/prograngers/backend/service/SolutionListSolutionServiceTest.java
Labels: ✅ test, 🌞 backend

#78 Feat/connect signup api
  frontend/Prog-rangers-main/package.json
  frontend/Prog-rangers-main/src/apis/singup.js
  frontend/Prog-rangers-main/src/components/SignUp/SignUpForm.jsx
  frontend/Prog-rangers-main/src/components/SignUp/signUpPage.js
Labels: ➕ feat, 🌝 frontend

#80 Feat : 로그인 api 연동
  frontend/Prog-rangers-main/src/App.js
  frontend/Prog-rangers-main/src/apis/signin.js
  frontend/Prog-rangers-main/src/apis/singup.js
  frontend/Prog-rangers-main/src/components/SignIn/DefaultSignInForm.jsx
  frontend/Prog-rangers-main/src/context/AuthContext.js
Labels: ➕ feat, 🌝 frontend

#83 [Fix] 82 header main page layout
  frontend/Prog-rangers-main/src/components/Header/Header.jsx
  frontend/Prog-rangers-main/src/components/Header/headerStyle.js
  frontend/Prog-rangers-main/src/components/Home/MainScrollDown.js
  frontend/Prog-rangers-main/src/components/Home/ScrollDownArrow.jsx
  frontend/Prog-rangers-main/src/pages/MainPage/MainPage.jsx
  frontend/Prog-rangers-main/src/pages/MainPage/MainPageIcons.js
  frontend/Prog-rangers-main/src/pages/MainPage/MainStyle.js
Labels: ♻ refactor, 🌝 frontend
